version: '3'
services:
  app:
    restart: unless-stopped
    image: opensourcepolitics/osp-app:latest
    volumes:
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - RAILS_ENV=production
    env_file:
      - .docker.env
    command: ["rails", "server", "-b", "0.0.0.0"]
    entrypoint: /app/docker-entrypoint.sh
    ports:
      - 3000:3000
    networks:
      - default

  sidekiq:
    restart: unless-stopped
    image: opensourcepolitics/osp-app:latest
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    environment:
      - RAILS_ENV=production
    env_file:
      - .docker.env
    networks:
    - default

volumes:
  node_modules: {}
  bundle: {}

networks:
  default:
    driver: bridge
