:concurrency: 5
:queues:
- default
- metrics
- mailers
- newsletter
- events

:schedule:
  CalculateAllMetrics:
    every: ['24h', first_in: '1m']
    class: CalculateAllMetricsJob
  PreloadOpenData:
    every: ['24h', first_in: '1m']
    class: PreloadOpenDataJob
  OrdersReminder:
    every: ['24h', first_in: '1m']
    class: OrdersReminderJob
