:concurrency: 5
:queues:
- default
- mailers
- newsletter
- events

:schedule:
  CalculateAllMetrics:
    every: ['24h', first_in: '1m']
    class: CalculateAllMetricsJob
  PreloadOpenDataJob:
    every: ['24h', first_in: '1m']
    class: PreloadOpenDataJob
