# frozen_string_literal: true

require "decidim/core/test/factories"
require "decidim/admin/test/factories"
require "decidim/accountability/test/factories"
require "decidim/assemblies/test/factories"
require "decidim/blogs/test/factories"
require "decidim/budgets/test/factories"
require "decidim/comments/test/factories"
require "decidim/meetings/test/factories"
require "decidim/pages/test/factories"
require "decidim/sortitions/test/factories"
require "decidim/surveys/test/factories"
require "decidim/system/test/factories"
require "decidim/proposals/test/factories"
require "decidim/accountability/test/factories"
require "decidim/participatory_processes/test/factories"
require "decidim/debates/test/factories"
